### ISSUE TITLE
error or warning when running line 196 of wetland_example.Rmd

### ISSUE THREAD

**Issue by rociojoo** [gordy2x/principles#2]
I think it's just a warning, but when I run

`em_water <- emmeans(rich_live,  ~ water_treatment + days , 
                    at = list(days = c(587,1261), fire_treatment = "ub"))`

I get 

```
Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed
Cannot use mode = "satterthwaite" because *lmerTest* package is not installed
```
This is probably just a warning and if so, could you add text in the .Rmd saying we could have this warning so that the reader is not surprised?

**Comment by rociojoo** [comment]
Same thing when running 
`em_fire <- emmeans(rich_live,  ~ water_treatment + fire_treatment , 
                   at = list(days = c(1261)))`

line 211

**Comment by gordy2x** [comment]
have put a comment
